name: ubuntu-ui-toolkit
version: '1.3.2085+16.10.20160915'
summary: Ubuntu UI Toolkit
description: |
  Qt is a cross-platform C++ application framework. Qt's primary feature
  is its rich set of widgets that provide standard GUI functionality.
  This package includes UITK.

grade: stable
confinement: strict

parts:
  ubuntu-ui-toolkit:
    plugin: make
    options:
        - QT_QPA_PLATFORM=minimal
    qt-version: qt5
    source-type: git
    source: https://github.com/tjyrinki/ubuntu-ui-toolkit.git
    source-branch: master
    build-packages:
        - dbus
        - dbus-test-runner
        - devscripts
        - gdb
        - libdbus-1-dev
        - liblttng-ust-dev
        - libnih-dbus-dev
        - libqt5svg5-dev
        - qtdeclarative5-unity-action-plugin
        - qtpim5-dev
    stage-packages:
        - libnih-dbus1
        - qtdeclarative5-unity-action-plugin
        - suru-icon-theme
        - ttf-ubuntu-font-family

